# Info about you; used to generate the landing page
role: Role
location: Location
about:
  overview: Overview of you
  likes: Thinks you like

# Projects you would like to show in the project column of the landing page
# Each project should have a title and a description. A url for the project can optionally be provided
projects:
  - title: Project name
    description: Project description
    url: http://example.com/
  - title: Other project
    description: Project description

# Network sites you would like to link to, e.g. GitHub, Twitter.
# Each site should have a url and a Font Awesome icon, e.g. fa-github for the GitHub icon.
# See http://fontawesome.io/icons/ for a complete list of Icons
network:
  - url: https://github.com/github
    icon: fa-github
  - url: https://twitter.com/twitter
    icon: fa-twitter

# A Google Analytics ID can optionally be provided for tracking
google_analytics:
